name: GitHub CI

on:

  pull_request:

  push:
    tags:
      - '*'

  schedule:
    - cron: 0 0 * * 0

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Prepare Environment
        run: docker system prune --all --force --volumes
      - name: Happy Eyeballs
        run: wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash

      - name: Check Kernel Config
        run: |
          kernDups="$(files/kernel-config.d/.check-dups.sh)"
          if [ -n "$kernDups" ]; then
            echo >&2 "KERNEL CONFIG DUPLICATES!"
            echo >&2 "$kernDups"
            exit 1
          fi

      - name: Build ISO
        run: |
          set -Eeuo pipefail -x
          docker build -t boot2docker/boot2docker .
          docker run --rm boot2docker/boot2docker > boot2docker.iso

      - uses: actions/upload-artifact@v2
        with:
          name: boot2docker.iso
          path: boot2docker.iso

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "boot2docker.iso"
          token: ${{ secrets.GITHUB_TOKEN }}